const refs = {
  
  addToWatchedBtn: document.querySelector('.addToWatchedBtn'),
  addToWatchedIcon: document.querySelector('.addToWatchedIcon'),
  addToQueueBtn: document.querySelector('.addToQueueBtn'),
  addToQueueIcon: document.querySelector('.addToQueueIcon'),
  btnContainer: document.querySelector('.btn-container'),
  detailsPage: document.querySelector('#detailsPage'),
  homePage: document.querySelector('#homePage'),
  homeRef: document.querySelector('.header__home-link'),
  lib: document.querySelector('.header__lib-link'),
  libImg: document.querySelector('.lib-list__item-img'),
  libList: document.querySelector('.lib-list'),
  libQueueBtn: document.querySelector('.lib_queue-link'),
  libWatchedBtn: document.querySelector('.lib_watched-link'),
  libraryPage: document.querySelector('#libraryPage'),
  logoRef: document.querySelector('.logo-container'),
  main: document.querySelector('.main'),
  moviesContainer: document.querySelector('.home-movie-list'),
  nextBtn: document.querySelector('.btn-next'),
  nextHomeBtn: document.querySelector('.btn-next-home'),
  pageBtn: document.querySelector('.btn-number'),
  popularPage: document.querySelector('.popular-movie-list'),
  prevBtn: document.querySelector('.btn-prev'),
  prevHomeBtn: document.querySelector('.btn-prev-home'),
  searchForm: document.querySelector('.header__form'),
  inputForm: document.querySelector('.header__form-input'),
  upButton: document.querySelector('.up-btn'),
  libListwWrap: document.querySelector('.lib-wrap'),
  libBtnList: document.querySelector('.lib_btn-list'),
}
export default refs;